### ISSUE TITLE
Upgrade to Red-DiscordBot 3.0.0rc3.*

### ISSUE THREAD

**Issue by NNTin** [NNTin/Red-kun#3]
Red-DiscordBot Release Candidate 3 has been released.
It currently uses RC2. This needs to be updated to RC3.

**Comment by AhmedXL** [comment]
Please update it

**Comment by AhmedXL** [comment]
Could not find a version that satisfies the requirement pyBarcode==0.7 (from -r /tmp/build_6b378a3b9ae7b0e2af4011830ca13e3e/requirements.txt (line 27)) (from versions: )
       No matching distribution found for pyBarcode==0.7 (from -r /tmp/build_6b378a3b9ae7b0e2af4011830ca13e3e/requirements.txt (line 27))
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by NNTin** [comment]
I know work has to be done but I'm lacking time. I got a new job during which I can't do anything from Mo-Fr. On many of the weekends I have something planned with my friends since I couldn't do it during work days. Then there are the weekly chores and grocery shopping. Finally I have my free time in which I have other projects I've been eager to do (moved into a new apartment and have been looking into home automations) or can relax and watch some movies.  

I really lack the motivation of maintaining this project because last time when it was working there wasn't a lot of people interested in using it. And at that time the Heroku solution was working flawlessly - including audio support through lavalink and being 99.9% online (it goes everday offline for a brief moment due to Heroku's limitation). So if I have time I will probably work on something else.

What I want to say is this project is probably dead. Maybe I will revive it someday or if someone else is working on Heroku support I can take a look.

**Comment by AhmedXL** [comment]
everytime i try to ask for help on red support server they keep saying we don't support heroku
and there is so much hate towards heroku when it comes to selfhosting
i will try to learn how to fix that issue, i am newbie when it comes to any of this
Thank you anyway
and you made me happy that you got a new job 🥇 
this is a side project anyway :D

**Comment by NNTin** [comment]
Closing in favor of https://github.com/NNTin/Red-kun/issues/6
